BOT_TOKEN = ""
API_HASH = ""
SESSION_NAME = "bot_session"
REPORT_CHAT_ID = 0

GROQ_VISION_MODEL = ""
GOOGLE_KEYS = []
GROQ_KEYS = []
TELEGRAPH_TOKEN = ""
GEMINI_MODEL = ""
GROQ_MODEL = ""
SEARCH_PROVIDER = ""
TAVILY_API_KEY = ""

DB_PATH = "stomat_bot.db"
SUMMARY_INTERVAL = 0
MAX_MSGS = 0
REPORT_HOUR = 0
